version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - config.yml
    ports:
      - "30000:30000"
      - "31000:31000"
    container_name: resource